// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
